apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-pipeline-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-pipeline-demo
  template:
    metadata:
      labels:
        app: secure-pipeline-demo
    spec:
      automountServiceAccountToken: false
      containers:
        - name: secure-pipeline-demo
          image: secure-pipeline-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
