name: CI/CD - Build & Push to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-secure-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test -- --coverage

      - name: Build Docker image
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: docker build -t ${DOCKERHUB_REPO}:latest .

      - name: Trivy Vulnerability Scan
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.DOCKERHUB_REPO }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test

      - name: GitLeaks Secret Detection
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --no-git --redact --exit-code 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        env:
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: docker push ${DOCKERHUB_REPO}:latest
      